/*
aesdsocket.c - A simple TCP socket server that listens on a specified port and echoes back any data received from clients
Author: Muthuu SVS
Date: 02-12-2026
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <syslog.h>
#include <signal.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>

#define PORT 9000
#define BUFFER_SIZE 1024

//global flag
static volatile sig_atomic_t exit_requested = 0;

//string to store data received from client
const char *outputfile = "/var/tmp/aesdsocketdata";

//this function was partial created with ChatGPT
//link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
//signal handler for graceful shutdown
static void signal_handler(int signum)
{
    (void)signum;

    int saved_errno = errno;
    exit_requested = 1;//set global flag
    errno = saved_errno;
}

//this function was fully generated by ChatGPT
//link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
//helper function to write byte by byte
static int write_all(int fd, const char *buf, size_t len)
{
    size_t off = 0;
    while (off < len) {
        ssize_t w = write(fd, buf + off, len - off);
        if (w < 0) return -1;
        off += (size_t)w;
    }
    return 0;
}

//this function was fully generated by ChatGPT
//link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
//helper function to send byte by byte
static int send_all(int fd, const char *buf, size_t len)
{
    size_t off = 0;
    while (off < len) {
        ssize_t s = send(fd, buf + off, len - off, 0);
        if (s < 0) return -1;
        off += (size_t)s;
    }
    return 0;
}

//this function was fully generated by ChatGPT
//link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
//helper function to daemonize the program when -d is specified
static int daemonize(void)
{
    pid_t pid = fork();
    if (pid < 0) {
        return -1;
    }
    if (pid > 0) {
        // Parent exits
        exit(0);
    }

    // Child continues in a new session
    if (setsid() < 0) {
        return -1;
    }

    // Second fork to prevent reacquiring a controlling terminal
    pid = fork();
    if (pid < 0) {
        return -1;
    }
    if (pid > 0) {
        exit(0);
    }

    umask(0);
    if (chdir("/") < 0) {
        return -1;
    }

    // Redirect stdin/stdout/stderr to /dev/null
    int fd = open("/dev/null", O_RDWR);
    if (fd < 0) {
        return -1;
    }

    (void)dup2(fd, STDIN_FILENO);
    (void)dup2(fd, STDOUT_FILENO);
    (void)dup2(fd, STDERR_FILENO);

    if (fd > STDERR_FILENO) {
        close(fd);
    }

    return 0;
}

int main(int argc, char *argv[])
{
    int server_fd, new_socket;
    struct sockaddr_in address;
    socklen_t addrlen = sizeof(address);
    char buffer[BUFFER_SIZE];

    //this code section was fully generated by ChatGPT
    //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
    //parse daemon option -d
    int run_as_daemon = 0;
    if (argc == 2 && strcmp(argv[1], "-d") == 0)
    {
        run_as_daemon = 1;
    }
    else if (argc != 1)
    {
        fprintf(stderr, "Usage: %s [-d]\n", argv[0]);
        return -1;
    }

    //open syslog
    openlog("aesdsocket", LOG_PID, LOG_USER);

    //this code section block was fully generated with ChatGPT
    //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = signal_handler;
    sigemptyset(&sa.sa_mask);

    // Choice: no SA_RESTART so accept()/recv() can break out with EINTR
    sa.sa_flags = 0;

    if (sigaction(SIGINT, &sa, NULL) == -1)
    {
        perror("sigaction SIGINT failed");
        closelog();
        return -1;
    }
    if (sigaction(SIGTERM, &sa, NULL) == -1)
    {
        perror("sigaction SIGTERM failed");
        closelog();
        return -1;
    }

    // Create socket file descriptor
    server_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (server_fd < 0)
    {
        perror("socket failed");
        closelog();
        return -1;
    }

    //this code section was fully generated by ChatGPT
    //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
    //recommended: allow quick restart without "Address already in use"
    int opt = 1;
    if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)) < 0)
    {
        perror("setsockopt SO_REUSEADDR failed");
        close(server_fd);
        closelog();
        return -1;
    }

    // Bind the socket to the port
    memset(&address, 0, sizeof(address));
    address.sin_family = AF_INET;
    address.sin_addr.s_addr = INADDR_ANY;
    address.sin_port = htons(PORT);

    if (bind(server_fd, (struct sockaddr *)&address, sizeof(address)) < 0)
    {
        perror("bind failed");
        close(server_fd);
        closelog();
        return -1;
    }

    //this code section was fully generated by ChatGPT
    //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
    //daemonize if requested
    if (run_as_daemon)
    {
        if (daemonize() < 0)
        {
            syslog(LOG_ERR, "Failed to daemonize: %s", strerror(errno));
            closelog();
            return -1;
        }
    }

    // Listen for incoming connections
    if (listen(server_fd, 3) < 0)
    {
        perror("listen failed");
        close(server_fd);
        closelog();
        return -1;
    }

    while (1)
    {
        // Accept a new connection
        new_socket = accept(server_fd, (struct sockaddr *)&address, &addrlen);
        if (new_socket < 0)
        {
            if (errno == EINTR && exit_requested)
            {
                break;
            }
            perror("accept failed");
            continue;
        }

        //this code section was modified using help from ChatGPT
        //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
        char ipstr[INET_ADDRSTRLEN];
        inet_ntop(AF_INET, &address.sin_addr, ipstr, sizeof(ipstr));
        syslog(LOG_INFO, "Accepted connection from %s", ipstr);

        // Initialize accumulated data buffer for storing partial/complete packets
        size_t accumulated_size = 0;             // Current size of accumulated data
        size_t allocated_size = BUFFER_SIZE;     // Currently allocated memory (capacity)
        char *accumulated_data = (char *)malloc(allocated_size);

        if (accumulated_data == NULL)
        {
            syslog(LOG_ERR, "malloc failed for accumulated_data");
            close(new_socket);
            continue;
        }

        accumulated_data[0] = '\0';

        // Receive data in a loop until connection closes
        while (1)
        {
            //this code section was partially generated by ChatGPT
            //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
            //if signal is caught, stop receiving new data (finish current connection cleanly)
            if (exit_requested)
            {
                break;
            }

            // Receive chunk of data from socket
            int valread = recv(new_socket, buffer, BUFFER_SIZE, 0);

            // Handle recv errors and connection closure
            if (valread < 0)
            {
                if (errno == EINTR && exit_requested)
                {
                    break;
                }
                perror("recv failed");
                syslog(LOG_ERR, "recv error from %s", ipstr);
                break;
            }

            if (valread == 0)
            {
                // Connection closed by client
                break;
            }

            //this code section was fully generated by ChatGPT
            //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
            //Ensure capacity for new data plus null terminator (avoid overflow)
            size_t needed = accumulated_size + (size_t)valread + 1; // +1 for '\0'
            if (needed > allocated_size)
            {
                size_t new_size = allocated_size;
                while (new_size < needed)
                {
                    new_size *= 2;
                }

                char *temp = (char *)realloc(accumulated_data, new_size);
                if (temp == NULL)
                {
                    syslog(LOG_ERR, "realloc failed, closing connection");
                    goto connection_cleanup;
                }
                accumulated_data = temp;
                allocated_size = new_size;
            }

            // Copy received data into accumulated buffer
            memcpy(accumulated_data + accumulated_size, buffer, (size_t)valread);
            accumulated_size += (size_t)valread;

            // Null-terminate the buffer for string function compatibility
            accumulated_data[accumulated_size] = '\0';

            // Process complete packets (lines terminated by newline)
            char *packet_end;
            while ((packet_end = strchr(accumulated_data, '\n')) != NULL)
            {
                // Calculate packet length including the newline
                size_t packet_len = (size_t)(packet_end - accumulated_data + 1);

                // Open (or create) output file in append mode and write packet
                int output_fd = open(outputfile, O_WRONLY | O_CREAT | O_APPEND, 0644);
                if (output_fd < 0)
                {
                    perror("open failed");
                    syslog(LOG_ERR, "Failed to open %s for writing", outputfile);
                }
                else
                {
                    //this code section was modified using help from ChatGPT
                    //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
                    //Write packet to file (includes newline) - use write_all() to handle partial writes
                    if (write_all(output_fd, accumulated_data, packet_len) < 0)
                    {
                        perror("write failed");
                        syslog(LOG_ERR, "Failed to write packet to %s", outputfile);
                    }
                    close(output_fd);

                    // Open output file for reading
                    int read_fd = open(outputfile, O_RDONLY);
                    if (read_fd < 0)
                    {
                        perror("open for reading failed");
                        syslog(LOG_ERR, "Failed to open %s for reading", outputfile);
                    }
                    else
                    {
                        //this code section was modified using help from ChatGPT
                        //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
                        //Read and send file contents in chunks, use send_all() to handle partial sends
                        ssize_t bytes_read;
                        while ((bytes_read = read(read_fd, buffer, BUFFER_SIZE)) > 0)
                        {
                            if (send_all(new_socket, buffer, (size_t)bytes_read) < 0)
                            {
                                perror("send failed");
                                syslog(LOG_ERR, "Failed to send data to client %s", ipstr);
                                break;
                            }
                        }

                        // Check for read error
                        if (bytes_read < 0)
                        {
                            perror("read failed");
                            syslog(LOG_ERR, "Failed to read from %s", outputfile);
                        }

                        close(read_fd);
                    }
                }

                // Remove processed packet from accumulated buffer
                accumulated_size -= packet_len;
                memmove(accumulated_data, accumulated_data + packet_len, accumulated_size);

                // Re-null-terminate after shifting data
                accumulated_data[accumulated_size] = '\0';
            }
        }

connection_cleanup:
        // Free dynamically allocated memory
        free(accumulated_data);

        // Close the connection
        close(new_socket);
        syslog(LOG_INFO, "Closed connection from %s", ipstr);

        // If a signal was requested during connection handling, exit after cleanup
        if (exit_requested)
        {
            break;
        }
    }

    //graceful exit only breaks when signal is caught
    syslog(LOG_INFO, "Caught signal, exiting");
    close(server_fd);
    unlink(outputfile);
    closelog();
    return 0;
}
