/*
aesdsocket.c - A simple TCP socket server that listens on a specified port and echoes back any data received from clients
Author: Muthuu SVS
Date: 02-12-2026
*/
//--------------------------------------------------
// Include necessary header files
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <syslog.h>
#include <signal.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/queue.h>
#include <pthread.h>
#include <errno.h>
//--------------------------------------------------
//MACROS
#define PORT 9000
#define BUFFER_SIZE 1024


//--------------------------------------------------
//globals
//global flag
static volatile sig_atomic_t exit_requested = 0;
static int server_fd = -1;//global listen socket fd, set to -1 when shutting down to indicate no new connections should be accepted

//string to store data received from client
const char *outputfile = "/var/tmp/aesdsocketdata";

//this code section was fully generated by ChatGPT
//link to chat session: https://chatgpt.com/share/69923ef5-a484-8008-b888-fa99fb164614
// pidfile for start-stop-daemon integration
static const char *pidfile = "/var/run/aesdsocket.pid";

//pthreads mutexs
static pthread_mutex_t file_mutex = PTHREAD_MUTEX_INITIALIZER;//for /var/tmp/aesdsocketdata file access
static pthread_mutex_t list_mutex = PTHREAD_MUTEX_INITIALIZER;//for linked list of threads

//Thread Node using queue.h
struct thread_node 
{
    pthread_t thread_id;
    int client_fd;
    volatile int completed;//1 = thread completed processing, 0 = still running
    char ipstr[INET_ADDRSTRLEN];//store client IP for logging on thread completion
    SLIST_ENTRY(thread_node) entries;
};

SLIST_HEAD(thread_list_head, thread_node);
static struct thread_list_head thread_list = SLIST_HEAD_INITIALIZER(thread_list);




//------------------------------------------------------
//helper functions

static void cleanup_threads(void)
{
    struct thread_node *node;
    while (!SLIST_EMPTY(&thread_list)) 
    {
        node = SLIST_FIRST(&thread_list);
        pthread_join(node->thread_id, NULL);
        close(node->client_fd);
        SLIST_REMOVE_HEAD(&thread_list, entries);
        free(node);
    }
}


// write current PID to pidfile (called after daemonize so PID is the real daemon PID)
static int write_pidfile(const char *path)
{
    int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) {
        return -1;
    }

    char buf[32];
    int len = snprintf(buf, sizeof(buf), "%ld\n", (long)getpid());
    if (len < 0 || (size_t)len >= sizeof(buf)) {
        close(fd);
        errno = EINVAL;
        return -1;
    }

    ssize_t w = write(fd, buf, (size_t)len);
    close(fd);

    if (w != (ssize_t)len) {
        return -1;
    }
    return 0;
}

//this function was partial created with ChatGPT
//link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
//signal handler for graceful shutdown
static void signal_handler(int signum)
{
    (void)signum;

    int saved_errno = errno;
    exit_requested = 1;//set global flag

    int fd = server_fd;
    server_fd = -1;//set to invalid value to indicate shutdown in progress
    if (fd != -1) 
    {
        close(fd);
    }
    errno = saved_errno;
}

//this function was fully generated by ChatGPT
//link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
//helper function to write byte by byte
static int write_all(int fd, const char *buf, size_t len)
{
    size_t off = 0;
    while (off < len) {
        ssize_t w = write(fd, buf + off, len - off);
        if (w < 0) return -1;
        off += (size_t)w;
    }
    return 0;
}

//this function was fully generated by ChatGPT
//link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
//helper function to send byte by byte
static int send_all(int fd, const char *buf, size_t len)
{
    size_t off = 0;
    while (off < len) {
        ssize_t s = send(fd, buf + off, len - off, 0);
        if (s < 0) return -1;
        off += (size_t)s;
    }
    return 0;
}

//this function was fully generated by ChatGPT
//link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
//helper function to daemonize the program when -d is specified
static int daemonize(void)
{
    pid_t pid = fork();
    if (pid < 0) {
        return -1;
    }
    if (pid > 0) {
        // Parent exits
        exit(0);
    }

    // Child continues in a new session
    if (setsid() < 0) {
        return -1;
    }

    // Second fork to prevent reacquiring a controlling terminal
    pid = fork();
    if (pid < 0) {
        return -1;
    }
    if (pid > 0) {
        exit(0);
    }

    umask(0);
    if (chdir("/") < 0) {
        return -1;
    }

    // Redirect stdin/stdout/stderr to /dev/null
    int fd = open("/dev/null", O_RDWR);
    if (fd < 0) {
        return -1;
    }

    (void)dup2(fd, STDIN_FILENO);
    (void)dup2(fd, STDOUT_FILENO);
    (void)dup2(fd, STDERR_FILENO);

    if (fd > STDERR_FILENO) {
        close(fd);
    }

    return 0;
}

//this function was fully generated by ChatGPT
//link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
//helper function to append a packet to the output file and then send the full file to the client
static int append_packet_and_send_file(int client_fd, const char *packet, size_t packet_len, char *io_buf, size_t io_buf_len)
{
    // Append packet to file
    int output_fd = open(outputfile, O_WRONLY | O_CREAT | O_APPEND, 0644);
    if (output_fd < 0)
    {
        return -1;
    }

    if (write_all(output_fd, packet, packet_len) < 0)
    {
        close(output_fd);
        return -1;
    }
    close(output_fd);

    // Send full file back to client (streaming)
    int read_fd = open(outputfile, O_RDONLY);
    if (read_fd < 0)
    {
        return -1;
    }

    ssize_t bytes_read;
    while ((bytes_read = read(read_fd, io_buf, io_buf_len)) > 0)
    {
        if (send_all(client_fd, io_buf, (size_t)bytes_read) < 0)
        {
            close(read_fd);
            return -1;
        }
    }

    close(read_fd);

    if (bytes_read < 0)
    {
        return -1;
    }

    return 0;
}

//handles one client connection independently
//this code block is based on original per-connection logic moved from main()
//modified to operate inside a pthread and use thread_node struct for client info and logging
static void *connection_thread(void *arg)
{
    struct thread_node *node = (struct thread_node *)arg;
    int new_socket = node->client_fd;

    struct sockaddr_in address;
    socklen_t addrlen = sizeof(address);

    char buffer[BUFFER_SIZE];

    // Initialize accumulated data buffer for storing partial/complete packets
    size_t accumulated_size = 0;             // Current size of accumulated data
    size_t allocated_size = BUFFER_SIZE;     // Currently allocated memory (capacity)
    char *accumulated_data = (char *)malloc(allocated_size);

    if (accumulated_data == NULL) {
        syslog(LOG_ERR, "malloc failed for accumulated_data");
        goto thread_cleanup;
    }

    accumulated_data[0] = '\0';

    // Receive data in a loop until connection closes
    while (1)
    {
         //this code section was partially generated by ChatGPT
        //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
        //if signal is caught, stop receiving new data (finish current connection cleanly)
        if (exit_requested) {
            break;
        }

        // Receive chunk of data from socket
        int valread = recv(new_socket, buffer, BUFFER_SIZE, 0);

        // Handle recv errors and connection closure
        if (valread < 0)
        {
            if (errno == EINTR && exit_requested) {
                break;
            }
            syslog(LOG_ERR, "recv error from %s: %s", node->ipstr, strerror(errno));
            break;
        }

        if (valread == 0)// Connection closed by client
        {
            //this code section was fully generated by ChatGPT
            //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
            //flush any remaining data in accumulated buffer to file before closing connection
            //could be partial packet without newline, but we will write it anyway to avoid data loss
            if (accumulated_size > 0)
            {
                if (append_packet_and_send_file(new_socket, accumulated_data, accumulated_size, buffer, BUFFER_SIZE) < 0)
                {
                    syslog(LOG_ERR, "Failed to append/send final packet for client %s", node->ipstr);
                    goto thread_cleanup;
                }
                //reset accumulated buffer
                accumulated_size = 0;
                accumulated_data[0] = '\0';
            }
            break;
        }

        //this code section was fully generated by ChatGPT
        //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
        //Ensure capacity for new data plus null terminator (avoid overflow)
        size_t needed = accumulated_size + (size_t)valread + 1;
        if (needed > allocated_size)
        {
            size_t new_size = allocated_size;
            while (new_size < needed) {
                new_size *= 2;
            }

            char *temp = (char *)realloc(accumulated_data, new_size);
            if (temp == NULL)
            {
                syslog(LOG_ERR, "realloc failed, closing connection");
                goto thread_cleanup;
            }
            accumulated_data = temp;
            allocated_size = new_size;
        }

        //copy received data into accumulated buffer and update size
        memcpy(accumulated_data + accumulated_size, buffer, (size_t)valread);
        accumulated_size += (size_t)valread;

        //null terminate the buffer for string function compatibility (strchr in packet processing)
        accumulated_data[accumulated_size] = '\0';


        //this code section was partially generated by ChatGPT
        //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
        //Process complete packets (lines terminated by newline) using append_packet_and_send_file()
        char *packet_end;
        while ((packet_end = strchr(accumulated_data, '\n')) != NULL)
        {
            size_t packet_len = (size_t)(packet_end - accumulated_data + 1);

            if (append_packet_and_send_file(new_socket, accumulated_data, packet_len, buffer, BUFFER_SIZE) < 0)
            {
                syslog(LOG_ERR, "Failed to append/send packet for client %s", node->ipstr);
                goto thread_cleanup;
            }
            //Remove processed packet from accumulated buffer 
            accumulated_size -= packet_len;
            memmove(accumulated_data, accumulated_data + packet_len, accumulated_size);
            
            //null terminate after shifting data
            accumulated_data[accumulated_size] = '\0';
        }
    }

thread_cleanup:
    if (accumulated_data)
    {
        free(accumulated_data);
    } 

    close(new_socket);
    node->client_fd = -1;
    syslog(LOG_INFO, "Closed connection from %s", node->ipstr);

    node->completed = 1;
    return NULL;
}


//----------------------------------------
//socket program main loop
int main(int argc, char *argv[])
{
    int new_socket;
    struct sockaddr_in address;
    socklen_t addrlen = sizeof(address);
    char buffer[BUFFER_SIZE];

    //this code section was fully generated by ChatGPT
    //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
    //parse daemon option -d
    int run_as_daemon = 0;
    if (argc == 2 && strcmp(argv[1], "-d") == 0)
    {
        run_as_daemon = 1;
    }
    else if (argc != 1)
    {
        fprintf(stderr, "Usage: %s [-d]\n", argv[0]);
        return -1;
    }

    //open syslog
    openlog("aesdsocket", LOG_PID, LOG_USER);

    //this code section block was fully generated with ChatGPT
    //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
    //setup signal handling
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = signal_handler;
    sigemptyset(&sa.sa_mask);

    // Choice: no SA_RESTART so accept()/recv() can break out with EINTR
    sa.sa_flags = 0;

    if (sigaction(SIGINT, &sa, NULL) == -1)
    {
        perror("sigaction SIGINT failed");
        closelog();
        return -1;
    }
    if (sigaction(SIGTERM, &sa, NULL) == -1)
    {
        perror("sigaction SIGTERM failed");
        closelog();
        return -1;
    }

    // Create socket file descriptor
    server_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (server_fd < 0)
    {
        perror("socket failed");
        closelog();
        return -1;
    }

    //this code section was fully generated by ChatGPT
    //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
    //recommended: allow quick restart without "Address already in use"
    int opt = 1;
    if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)) < 0)
    {
        perror("setsockopt SO_REUSEADDR failed");
        close(server_fd);
        closelog();
        return -1;
    }

    // Bind the socket to the port
    memset(&address, 0, sizeof(address));
    address.sin_family = AF_INET;
    address.sin_addr.s_addr = INADDR_ANY;
    address.sin_port = htons(PORT);

    if (bind(server_fd, (struct sockaddr *)&address, sizeof(address)) < 0)
    {
        perror("bind failed");
        close(server_fd);
        closelog();
        return -1;
    }

    //this code section was partially generated by ChatGPT
    //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
    //link to 2nd chat session: https://chatgpt.com/share/69923ef5-a484-8008-b888-fa99fb164614
    //daemonize if requested (requirement: fork after ensuring bind succeeds)
    if (run_as_daemon)
    {
        if (daemonize() < 0)
        {
            syslog(LOG_ERR, "Failed to daemonize: %s", strerror(errno));
            close(server_fd);
            closelog();
            return -1;
        }
        //write pidfile after daemonize so PID is the final daemon PID
        if (write_pidfile(pidfile) < 0)
        {
            syslog(LOG_ERR, "Failed to write pidfile %s: %s", pidfile, strerror(errno));
            close(server_fd);
            closelog();
            return -1;
        }
    }

    // Listen for incoming connections
    if (listen(server_fd, 3) < 0)
    {
        perror("listen failed");
        close(server_fd);
        closelog();
        return -1;
    }

    while (1)
    {
        //this code section was partially generated by ChatGPT
        //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
        //reset addrlen before each accept (some implementations may modify it)
        addrlen = sizeof(address);

        // Accept a new connection
        new_socket = accept(server_fd, (struct sockaddr *)&address, &addrlen);
        if (new_socket < 0)
        {
            //split because multiple conditions to check for, but we want to break on exit_requested and continue on EINTR without exit_requested
            if (exit_requested)
            {
                break;
            }
            if (errno == EINTR)
            {
                continue;
            }
            perror("accept failed");
            continue;
        }

        //this code section was modified using help from ChatGPT
        //link to chat session: https://chatgpt.com/share/6990b762-3dd8-8008-b70d-03f9fc138aca
        char ipstr[INET_ADDRSTRLEN];
        inet_ntop(AF_INET, &address.sin_addr, ipstr, sizeof(ipstr));
        syslog(LOG_INFO, "Accepted connection from %s", ipstr);

        //Allocate thread node
        struct thread_node *node = (struct thread_node *)calloc(1, sizeof(struct thread_node));
        if(node == NULL)
        {
            syslog(LOG_ERR, "calloc failed for thread_node");
            close(new_socket);
            continue;
        }

        //init node with client info
        node->client_fd = new_socket;
        strncpy(node->ipstr, ipstr, sizeof(node->ipstr) - 1);
        node->ipstr[sizeof(node->ipstr) - 1] = '\0';    
        node->completed = 0;

        // Add node to thread list
        pthread_mutex_lock(&list_mutex);
        SLIST_INSERT_HEAD(&thread_list, node, entries);
        pthread_mutex_unlock(&list_mutex);

        // Create thread to handle connection
        if (pthread_create(&node->thread_id, NULL, connection_thread, node) != 0)
        {
            syslog(LOG_ERR, "Failed to create thread for client %s", ipstr);
            // Cleanup node and close connection
            pthread_mutex_lock(&list_mutex);
            SLIST_REMOVE(&thread_list, node, thread_node, entries);
            pthread_mutex_unlock(&list_mutex);

            free(node);
            close(new_socket);
            continue;
        }

        //join completed threads to clean up resources (non-blocking join)
        pthread_mutex_lock(&list_mutex);
        struct thread_node *iter;
        SLIST_FOREACH(iter, &thread_list, entries)//iterate through thread list to find completed threads
        {
            if (iter->completed)//completed flag
            {
                SLIST_REMOVE(&thread_list, iter, thread_node, entries);
                pthread_mutex_unlock(&list_mutex);//unlock before join to avoid deadlock if thread tries to lock list_mutex during cleanup
                pthread_join(iter->thread_id, NULL);

                close(iter->client_fd);
                free(iter);

                pthread_mutex_lock(&list_mutex);//re-lock after join to continue iterating safely
            }
        }
        pthread_mutex_unlock(&list_mutex);
    }

    //graceful exit only breaks when signal is caught
    syslog(LOG_INFO, "Caught signal, exiting");

    // Cleanup: join any remaining threads and free resources
    //Request active threads to exit by closing their sockets
    pthread_mutex_lock(&list_mutex);
    struct thread_node *node;
    SLIST_FOREACH(node, &thread_list, entries)
    {
        if (node->client_fd != -1)
        {
            shutdown(node->client_fd, SHUT_RDWR);
            close(node->client_fd);
            node->client_fd = -1;
        }
    }
    pthread_mutex_unlock(&list_mutex);

    //Join all remaining threads
    while (!SLIST_EMPTY(&thread_list))
    {
        struct thread_node *node = SLIST_FIRST(&thread_list);
        SLIST_REMOVE_HEAD(&thread_list, entries);
        pthread_join(node->thread_id, NULL);
        free(node);
    }

    //cleanup files and syslog
    close(server_fd);
    unlink(outputfile);
    unlink(pidfile);
    closelog();
    return 0;
}
