#!/bin/sh
#this script was fully generated by ChatGPT
#link to chat session: https://chatgpt.com/share/69923ef5-a484-8008-b888-fa99fb164614
set -eu

NAME="aesdsocket"
DAEMON="/usr/bin/${NAME}"
PIDFILE="/var/tmp/${NAME}.pid"

start() {
    echo "Starting $NAME..."
    [ -x "$DAEMON" ] || { echo "Error: $DAEMON not executable"; exit 1; }

    # If pidfile exists and process is alive, treat as already running
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE" 2>/dev/null)" 2>/dev/null; then
        echo "$NAME already running"
        exit 0
    fi

    # Start the program in daemon mode (required: -d)
    start-stop-daemon -S -q -x "$DAEMON" -- -d

    # Best-effort wait for pidfile to appear (daemon writes it after double-fork)
    i=0
    while [ $i -lt 20 ]; do
        [ -f "$PIDFILE" ] && exit 0
        i=$((i+1))
        usleep 50000 2>/dev/null || sleep 0.05
    done

    echo "Warning: $PIDFILE not created; stop may not work reliably"
    exit 0
}

stop() {
    echo "Stopping $NAME..."
    if [ -f "$PIDFILE" ]; then
        start-stop-daemon -K -q -p "$PIDFILE" --signal TERM --retry 5 || true
        rm -f "$PIDFILE"
        exit 0
    fi

    # No pidfile: still try to stop by executable as best-effort
    start-stop-daemon -K -q -x "$DAEMON" --signal TERM --retry 5 || true
    exit 0
}

case "${1:-}" in
    start) start ;;
    stop) stop ;;
    restart) stop; start ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 2
        ;;
esac
